apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: web-preview
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000