apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web-canary
spec:
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0

      analysis:
        templates:
          - templateName: test-web-canary-analysis
        args:
          - name: service-name
            value: web-canary
          - name: service-port
            value: "8080"
      steps:
        - setWeight: 10
        - pause:
            duration: 10s
        - setWeight: 30
        - pause: {}
        - setWeight: 50
        - pause: {}
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: web:v1
#          imagePullPolicy: Always

